#!/bin/python3
#Birthday Cake Candles

import math
import os
import random
import re
import sys

# Complete the birthdayCakeCandles function below.
def birthdayCakeCandles(ar):
    #We can use the below single line of code using predefined functions 
    #return ar.count(max(ar))
    
    #We can use iteration to find max and count
    max1=ar[0]
    count=0
    for i in ar:
        if(max1<i):
            max1=i
    for i in ar:
        if(max1==i):
            count+=1
    return count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ar_count = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = birthdayCakeCandles(ar)

    fptr.write(str(result) + '\n')

    fptr.close()
