#!/bin/python3
#Given an array of integers, calculate the fractions of its elements that are positive, negative, and are zeros. Print the decimal value of each fraction on a new line.
import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
def plusMinus(arr):
    minus=0
    plus=0
    zero=0
    size=len(arr)
    for i in arr:
        if(i<0):
            minus+=1
        elif i>0:
            plus+=1
        else:
            zero+=1
    print(round(plus/size,6))
    print(round(minus/size,6))
    print(round(zero/size,6))
        

if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
