#!/bin/python3
#Find absolute difference between the sums of the matrix's two diagonals
import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr,n):
    ldsum=0
    rdsum=0
    start=0
    end=n-1
    for i in range(n):
        for j in range(n):
            if i==j:
                ldsum+=arr[i][j]
            if i==start and j==end:
                rdsum+=arr[i][j]
                start+=1
                end-=1
    res=abs(ldsum-rdsum)
    return res


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split()))) 
    result = diagonalDifference(arr,n)

    fptr.write(str(result) + '\n')

    fptr.close()
