#!/bin/python3
#Pattern Printing
import math
import os
import random
import re
import sys

# Complete the staircase function below.
def staircase(n):
    for i in range(1,n+1):
        temp=i
        while(n-temp!=0):
            print(" ",end="")
            temp+=1
        temp=i
        while(temp!=0):
            print("#",end="")
            temp-=1
        print()


if __name__ == '__main__':
    n = int(input())

    staircase(n)
